-- Create the table for storing watch history
create table public.history (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Stores the Clerk User ID
  video_id text not null,
  url text not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add an index on user_id for faster lookups
create index history_user_id_idx on public.history (user_id);

-- Optional: Enable Row Level Security (RLS)
-- Note: Since you are using Clerk, standard Supabase auth.uid() won't work directly 
-- unless you configure custom JWTs. For a simple setup, you might leave RLS off 
-- or configure a policy based on your specific needs/integration.
alter table public.history enable row level security;

-- ALLOW ALL for now (Development Mode)
-- WARNING: This allows anyone with the anon key to read/write any history. 
-- You should restrict this in production.
create policy "Allow all access"
on public.history
for all
using (true)
with check (true);
